CREATE TABLE `contas_pagar` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `fornecedor` VARCHAR(150) NULL,
  `responsavel` VARCHAR(150) NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `data_pagamento` DATE NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pendente',
  `forma_pagamento` VARCHAR(30) NULL,
  `banco` VARCHAR(100) NULL,
  `recorrente` BOOLEAN NOT NULL DEFAULT false,
  `categoria` VARCHAR(80) NULL,
  `observacoes` TEXT NULL,
  `empresa_id` INTEGER NOT NULL,
  `criado_por` INTEGER NOT NULL,
  `criado` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `atualizado` DATETIME(3) NOT NULL,
  INDEX `contas_pagar_empresa_status_venc_idx` (`empresa_id`, `status`, `data_vencimento`),
  INDEX `contas_pagar_criado_por_idx` (`criado_por`),
  PRIMARY KEY (`id`),
  CONSTRAINT `contas_pagar_empresa_id_fkey` FOREIGN KEY (`empresa_id`) REFERENCES `empresas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `contas_pagar_criado_por_fkey` FOREIGN KEY (`criado_por`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `contas_receber` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `lead_id` INTEGER NOT NULL,
  `responsavel` VARCHAR(150) NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `data_recebimento` DATE NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pendente',
  `forma_recebimento` VARCHAR(30) NULL,
  `banco` VARCHAR(100) NULL,
  `recorrente` BOOLEAN NOT NULL DEFAULT false,
  `categoria` VARCHAR(80) NULL,
  `observacoes` TEXT NULL,
  `empresa_id` INTEGER NOT NULL,
  `criado_por` INTEGER NOT NULL,
  `criado` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `atualizado` DATETIME(3) NOT NULL,
  INDEX `contas_receber_empresa_status_venc_idx` (`empresa_id`, `status`, `data_vencimento`),
  INDEX `contas_receber_empresa_lead_idx` (`empresa_id`, `lead_id`),
  INDEX `contas_receber_criado_por_idx` (`criado_por`),
  PRIMARY KEY (`id`),
  CONSTRAINT `contas_receber_empresa_id_fkey` FOREIGN KEY (`empresa_id`) REFERENCES `empresas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `contas_receber_criado_por_fkey` FOREIGN KEY (`criado_por`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `contas_receber_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
